app/features/crypto/routes.py
from flask import (render_template, Blueprint, g, redirect,
                   request, current_app, abort, url_for, jsonify, make_response, json)

from flask_babel import _, refresh


crypto = Blueprint('crypto', __name__, template_folder='templates', url_prefix='/<lang_code>' )

# Multiligual Start
@crypto.url_defaults
def add_language_code(endpoint, values):
    values.setdefault('lang_code', g.lang_code)

@crypto.url_value_preprocessor
def pull_lang_code(endpoint, values):
    g.lang_code = values.pop('lang_code')

@crypto.before_request
def before_request():
    if g.lang_code not in current_app.config['LANGUAGES']:
        abort(404)

# Multiligual End

@crypto.route('/')
def index():
    return render_template('crypto/index.html', title=_('waramity portfolio'))

app/templates/main/aboutme.html
<style>
  .intro-header::before {
    transform: scaleX(0);
    transform-origin: bottom right;
  }

  .intro-header:hover::before {
    transform: scaleX(1);
    transform-origin: bottom left;
  }

  .intro-header::before {
    content: " ";
    display: block;
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    inset: 0 0 0 0;
    background: #7f6ed2;
    z-index: -1;
    transition: transform 0.3s ease;
  }

  .intro-header {
    position: relative;
  }
</style>

<h1 class="display-3 intro-header">
  {{_('Hello, I\'m Full stack Developer')}}
</h1>
<h6 class="fw-lighter fst-italic">
  {{_('* this website compatible for desktop')}}
</h6>

app/templates/main/experience.html
<style media="screen">
  .blog-post-box {
    position: relative;
    display: inline-block;
  }
  .blog-post-box span {
    position: relative;
    text-transform: none;
    z-index: 3;
    -webkit-transition: all 200ms linear;
    transition: all 200ms linear;
  }
  .blog-post-box:hover span {
  }

  .cursor.cursor-dot.active-blog-post-1,
  .cursor.cursor-dot.active-blog-post-2,
  .cursor.cursor-dot.active-blog-post-3,
  .cursor.cursor-dot.active-blog-post-4,
  .cursor.cursor-dot.active-blog-post-5,
  .cursor.cursor-dot.active-blog-post-6,
  .cursor.cursor-dot.active-blog-post-7,
  .cursor.cursor-dot.active-blog-post-8 {
    opacity: 0;
  }
  .cursor-shadow.active-blog-post-1,
  .cursor-shadow.active-blog-post-2,
  .cursor-shadow.active-blog-post-3,
  .cursor-shadow.active-blog-post-4,
  .cursor-shadow.active-blog-post-5,
  .cursor-shadow.active-blog-post-6,
  .cursor-shadow.active-blog-post-7,
  .cursor-shadow.active-blog-post-8 {
    --size: 160px;
    border-color: rgba(255, 255, 255, 0);
    border-width: 0;
    background-color: transparent;
    background-position: center center;
    background-repeat: no-repeat;
    background-size: cover;
    border-radius: 50%;
    z-index: 1;
  }
  .cursor-shadow.active-blog-post-1 {
    background-image: url("https://images.unsplash.com/photo-1585301079507-3d745e800105?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2831&q=80");
  }
  .cursor-shadow.active-blog-post-2 {
    background-image: url("https://i.ytimg.com/vi/I_A8NinGXr4/maxresdefault.jpg");
  }
  .cursor-shadow.active-blog-post-3 {
    background-image: url("https://miro.medium.com/v2/resize:fit:1200/1*SXdOXQCHWL3u3SDqloY3FQ.jpeg");
  }
  .cursor-shadow.active-blog-post-4 {
    background-image: url("https://engage-eu.s3-ap-southeast-1.amazonaws.com/uploads/images/final-2.width-1920.jpg");
  }
  .cursor-shadow.active-blog-post-5 {
    background-image: url("/static/data/main/course-square.jpeg");
  }
  .cursor-shadow.active-blog-post-6 {
    background-image: url("/static/data/main/kingsford.jpeg");
  }
  .cursor-shadow.active-blog-post-7 {
    background-image: url("https://www.fnsyrus.com/assets/images/shared/ob_logo.png?v=20191118");
  }
  .cursor-shadow.active-blog-post-8 {
    background-image: url("/static/data/main/thammasat.png");
  }

  @media (max-width: 991px) {
    .h5 {
      font-size: 1.2rem;
    }
    .section-title-wrap h1 {
      font-size: 4rem;
    }
    .blog-nav {
      font-size: 7vw;
    }
  }
</style>
<h1 class="display-3 mb-5">
  {{_('Experience')}}
</h1>

<div class="section padding-bottom-big over-hide">
  <div class="row">
    <div
      class="col-12 display-6 text-secondary mb-3"
      style="font-size: 1.8rem; line-height: 2.33em; letter-spacing: 0.05em;"
    >
      Born in
      <a href="#" class="cursor-link-blog-post-1">
        <div class="blog-post-box">
          <span class="h5">Chonburi, Bangkok 1996</span>
        </div>
      </a>
      , I found myself hooked on design and programming when my brother showed
      me his website at the age of 13 while attending

      <a href="#" class="cursor-link-blog-post-2">
        <div class="blog-post-box">
          <span class="h5">Assumption College Sriracha.</span>
        </div>
      </a>
      I started as a
      <a href="#" class="cursor-link-blog-post-3">
        <div class="blog-post-box">
          <span class="h5">Pirated game publisher</span>
        </div>
      </a>
      and soon discovered my passion. This led me to study at
      <a href="#" class="cursor-link-blog-post-4">
        <div class="blog-post-box">
          <span class="h5">Mahidol University.</span>
        </div>
      </a>
      In no time, I was working as an intern and part-time at
      <a href="#" class="cursor-link-blog-post-5">
        <div class="blog-post-box">
          <span class="h5">Course Square.</span>
        </div>
      </a>

      After graduated, I was hired by
      <a href="#" class="cursor-link-blog-post-6">
        <div class="blog-post-box">
          <span class="h5">Kingsford Company</span>
        </div>
      </a>
      as an IT Manager. Later, the company underwent a change, and I had to move
      to
      <a href="#" class="cursor-link-blog-post-7">
        <div class="blog-post-box">
          <span class="h5">Finansia Syrus Company</span>
        </div>
      </a>
      as an Investment Consultant. Not being familiar with finance. Then, I
      pursued Technology Business at
      <a href="#" class="cursor-link-blog-post-8">
        <div class="blog-post-box">
          <span class="h5">Thammasat University,</span>
        </div>
      </a>

      which eventually led me to leave the company to work on various projects
      with many people.
    </div>
  </div>
</div>

<script type="text/javascript">

  $(window).mousemove(function (e) {
    $(".cursor").css({
      left: e.pageX,
      top: e.pageY,
    });
  });
  $(".cursor-link")
    .on("mouseenter", function () {
      $(".cursor").addClass("active");
    })
    .on("mouseleave", function () {
      $(".cursor").removeClass("active");
    });
  for (let i = 1; i <= 8; i++) {
    const linkClass = `.cursor-link-blog-post-${i}`;
    const cursorClass = `active-blog-post-${i}`;

    $(linkClass)
      .on("mouseenter", function () {
        $(".cursor").addClass(cursorClass);
      })
      .on("mouseleave", function () {
        $(".cursor").removeClass(cursorClass);
      });
  }
</script>

app/templates/main/index.html
{% extends "common/_base.html" %} {% include "common/cursor.html" %} {% block
content %}
<div class="ms-5" style="margin-top: 30em; margin-bottom: 30rem;">
  {% include "main/aboutme.html" %}
</div>

<div class="container">
  <div class="p-5" id="experience-section">
    {% include "main/experience.html" %}
  </div>
  <div class="p-5" id="skill-section">
    {% include "main/skill.html" %}
  </div>

  <div id="system-architecture-section" class="m-5" style="margin-top: 10rem;">
    {% include "main/system-architecture.html" %}
  </div>
</div>

<div id="work-section">
  {% include "main/work.html" %}
</div>
{% include "main/want-to-up.html" %} {%endblock%}

app/templates/main/skill.html
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<h1 class="display-4 mb-4">Skill-Set</h1>

<div class="row">
  <div id="skill-card-root" class="container"></div>
</div>

app/templates/main/system-architecture.html
<style media="screen">
  img.sa-icon {
    -webkit-filter: grayscale(100%);
    -moz-filter: grayscale(100%);
    filter: grayscale(100%);
    transition: all 0.5s ease;
  }

  img.sa-icon:hover {
    -webkit-filter: grayscale(0%);
    -moz-filter: grayscale(0%);
    filter: grayscale(0%);
  }
</style>

<h2 class="text-white mb-5 text-center display-6">This website create from:</h2>

<div class="row">
  {% for icon in system_architecture_icons %}
  <div class="col">
    <img src="/static/data/main/{{icon}}" class="w-100 sa-icon" />
  </div>
  {% endfor %}
</div>

app/templates/main/want-to-up.html
<style>
  .want-to-up-btn {
    position: relative;
    text-align: center;
    font-family: "Poppins", sans-serif;
    font-weight: 900;
    color: #a3a3a3;
    font-size: 4vw;
    opacity: 0.2;
    transition: opacity 1s;
    transition-timing-function: ease-out;
    animation: glow 0.6s ease-in-out infinite alternate;
  }

  .want-to-up-btn:hover {
    opacity: 1;
    color: #ffffff;
  }

  @-webkit-keyframes glow {
    from {
      text-shadow: 0 0 10px #787777, 0 0 20px #787777, 0 0 30px #4a4e5c;
    }

    to {
      text-shadow: 0 0 20px #787777, 0 0 30px #565b70, 0 0 40px #565b70,
        0 0 50px #565b70, 0 0 70px #ffffff;
    }
  }
</style>
<div class="section padding-top-bottom over-hide background-dark">
  <div class="container">
    <div class="row">
      <div
        class="col-12 text-center"
        data-scroll-reveal="enter bottom move 30px over 0.5s after 0.2s"
      >
        <a href="#" class="want-to-up-btn cursor-link">want to go up?</a>
      </div>
    </div>
  </div>
</div>
<style media="screen"></style>

app/templates/main/work.html
<style>
  :root {
    --background-dark: #2d3548;
    --text-light: rgba(255, 255, 255, 0.6);
    --text-lighter: rgba(255, 255, 255, 0.9);
    --spacing-s: 8px;
    --spacing-m: 16px;
    --spacing-l: 24px;
    --spacing-xl: 32px;
    --spacing-xxl: 64px;
    --width-container: 1200px;
  }
  .hero-section {
    align-items: flex-start;
    display: flex;
    padding: var(--spacing-xxl) var(--spacing-l);
    justify-content: center;
    margin-bottom: 10rem;
  }

  .work-card-grid {
    display: grid;
    grid-template-columns: repeat(1, 1fr);
    grid-column-gap: var(--spacing-l);
    grid-row-gap: var(--spacing-l);
    max-width: var(--width-container);
    width: 100%;
  }

  @media (min-width: 540px) {
    .work-card-grid {
      grid-template-columns: repeat(2, 1fr);
    }
  }

  @media (min-width: 960px) {
    .work-card-grid {
      grid-template-columns: repeat(4, 1fr);
    }
  }

  .work-card {
    list-style: none;
    position: relative;
  }

  .work-card:before {
    content: "";
    display: block;
    padding-bottom: 150%;
    width: 100%;
  }

  .work-card__background {
    background-size: cover;
    background-position: center;
    border-radius: var(--spacing-l);
    bottom: 0;
    filter: brightness(0.75) saturate(1.2) contrast(0.85);
    left: 0;
    position: absolute;
    right: 0;
    top: 0;
    transform-origin: center;
    trsnsform: scale(1) translateZ(0);
    transition: filter 200ms linear, transform 200ms linear;
  }

  .work-card:hover .card__background {
    transform: scale(1.05) translateZ(0);
  }

  .work-card-grid:hover > .work-card:not(:hover) .work-card__background {
    filter: brightness(0.5) saturate(0) contrast(1.2) blur(20px);
  }

  .work-card__content {
    left: 0;
    padding: var(--spacing-l);
    position: absolute;
    top: 0;
  }

  .work-card__category {
    color: var(--text-light);
    font-size: 0.9rem;
    margin-bottom: var(--spacing-s);
    text-transform: uppercase;
  }

  .work-card__heading {
    color: var(--text-lighter);
    font-size: 1.9rem;
    text-shadow: 2px 2px 20px rgba(0, 0, 0, 0.2);
    line-height: 1.4;
    word-spacing: 100vw;
  }
</style>

<div class="section padding-top-big padding-bottom over-hide">
  <div class="container">
    <div class="row">
      <div class="col-12 section-title-wrap text-center parallax-fade-top">
        <p class="primary-color">my</p>
        <h1>work</h1>
      </div>
    </div>
  </div>
</div>

<link
  href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
  rel="stylesheet"
/>

<div class="hero-section">
  <div class="work-card-grid">
    <a class="work-card" href="{{ url_for('crypto.index') }}">
      <div
        class="work-card__background"
        style="
          background-image: url(https://images.unsplash.com/photo-1622630998477-20aa696ecb05?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1546&q=80);
        "
      ></div>
      <div class="work-card__content">
        <p class="work-card__category">Web Application</p>
        <h3 class="work-card__heading">Crypto Currency</h3>
      </div>
    </a>
    <a class="work-card" href="#">
      <div
        class="work-card__background"
        style="
          background-image: url(https://plus.unsplash.com/premium_photo-1665160824748-deb28c84bbe0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80);
        "
      ></div>
      <div class="work-card__content">
        <p class="work-card__category">Web Application</p>
        <h3 class="work-card__heading">Dating App</h3>
      </div>
    </a>

    <a class="work-card" href="#">
      <div
        class="work-card__background"
        style="
          background-image: url(https://images.unsplash.com/photo-1692606526099-551f34037811?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2127&q=80);
        "
      ></div>
      <div class="work-card__content">
        <p class="work-card__category">Web Application</p>
        <h3 class="work-card__heading">AI Image Hub</h3>
      </div>
    </a>

    <a
      class="work-card"
      href="https://www.facebook.com/profile.php?id=100088716401766"
    >
      <div
        class="work-card__background"
        style="
          background-image: url(https://mpost.io/wp-content/uploads/image-68-16.jpg);
        "
      ></div>
      <div class="work-card__content">
        <p class="work-card__category">Tutorial</p>
        <h3 class="work-card__heading">The deep pub</h3>
      </div>
    </a>
  </div>
</div>